# Generated by Django 3.1 on 2023-02-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanIteration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_flag', models.BooleanField()),
                ('angle', models.FloatField()),
                ('distance', models.FloatField()),
                ('quality', models.FloatField()),
                ('iteration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='radar_screen.scaniteration')),
            ],
        ),
    ]
