# Generated by Django 3.1 on 2023-02-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar_screen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaniteration',
            name='csv_string',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
